sudo: required

services:
  - docker

branches:
  only:
    - master

language: ruby

before_install:
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  - ./build.sh base
  - ./build.sh dev
